import { readFileSync, writeFileSync } from "fs";

const css = readFileSync(".tmp/styles.css", "utf8");
const content = `// AUTO-GENERATED by build — do not edit\nexport const COMPILED_CSS = ${JSON.stringify(css)};\n`;
writeFileSync("src/_compiled-styles.ts", content);
console.log(`✓ Embedded ${css.length} bytes of CSS`);
